### PR TITLE
Updated josdk version to 4.3.0

### PR DESCRIPTION
**Pull request by fsjovatsen**

### CODE REVIEW

**Comment by csviri** [comment]
Hi @fsjovatsen , thx, for PR, do you plan to work on a fix for the issues in the build? 
(or should I take a look :) )

**Comment by fsjovatsen** [comment]
> Hi @fsjovatsen , thx, for PR, do you plan to work on a fix for the issues in the build? (or should I take a look :) )

I can take a look during the weekend.

**Comment by csviri** [comment]
ok, thank you! let me know if need some help (although not sure available this weekend)

**Comment by csviri** [comment]
replaced by: https://github.com/java-operator-sdk/operator-framework-spring-boot-starter/pull/52

**Pull request closed without merging**
